# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

gem 'middleman-simple-thumbnailer', '2.0.0', :git => 'https://github.com/IRI-Research/middleman-simple-thumbnailer.git', :branch => 'support-middleman-v4.1'

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-compass', '>= 4.0.0'
gem 'middleman-autoprefixer'
gem 'middleman-sprockets', '>= 4.0.0.rc.1'
gem "middleman-blog"
gem "nokogiri"


gem 'middleman-deploy',  '2.0.0.pre.alpha', :git => 'https://github.com/middleman-contrib/middleman-deploy.git'
